
// Perplexity Bulk Export - Browser Console Script
// Generated by Claude Code - Paste into browser console and run

(async function PerplexityBulkExporter() {
    'use strict';

    console.log('🚀 Perplexity Bulk Export Script Starting...');

    // Configuration
    const CONFIG = {
        DELAY_BETWEEN_EXPORTS: 3000, // 3 seconds between exports
        MAX_RETRIES: 3,
        BATCH_SIZE: 5, // Process 5 at a time
        PROGRESS_UPDATE_INTERVAL: 1000
    };

    // Utility functions
    function sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }

    function sanitizeFilename(title) {
        return title
            .replace(/[<>:"/\|?*]/g, '_') // Remove invalid chars
            .replace(/\s+/g, ' ') // Normalize spaces
            .trim()
            .substring(0, 50); // Max 50 characters
    }

    function log(message, type = 'info') {
        const timestamp = new Date().toLocaleTimeString();
        const prefix = type === 'error' ? '❌' : type === 'success' ? '✅' : 'ℹ️';
        console.log(`[${timestamp}] ${prefix} ${message}`);
    }

    // Progress UI
    function createProgressUI() {
        const progressDiv = document.createElement('div');
        progressDiv.id = 'perplexity-export-progress';
        progressDiv.style.cssText = `
            position: fixed;
            top: 20px;
            right: 20px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px;
            border-radius: 12px;
            font-family: 'SF Pro Display', -apple-system, BlinkMacSystemFont, sans-serif;
            box-shadow: 0 8px 32px rgba(0,0,0,0.3);
            z-index: 10000;
            min-width: 320px;
            font-size: 14px;
            line-height: 1.4;
        `;
        document.body.appendChild(progressDiv);
        return progressDiv;
    }

    function updateProgress(current, total, status, errors = 0) {
        const progressDiv = document.getElementById('perplexity-export-progress');
        if (progressDiv) {
            const percentage = Math.round((current / total) * 100);
            const remaining = total - current;
            const errorRate = total > 0 ? Math.round((errors / total) * 100) : 0;

            progressDiv.innerHTML = `
                <div style="font-weight: 600; margin-bottom: 12px; font-size: 16px;">
                    🔄 Perplexity Bulk Export
                </div>
                <div style="margin-bottom: 8px;">
                    <div style="font-weight: 500;">Progress: ${current}/${total} (${percentage}%)</div>
                    <div style="background: rgba(255,255,255,0.2); height: 6px; border-radius: 3px; margin: 6px 0;">
                        <div style="background: #4ade80; height: 100%; width: ${percentage}%; border-radius: 3px; transition: width 0.3s ease;"></div>
                    </div>
                </div>
                <div style="font-size: 13px; opacity: 0.9;">
                    <div>Status: ${status}</div>
                    <div>Remaining: ${remaining}</div>
                    <div>Errors: ${errors} (${errorRate}%)</div>
                    <div>Time: ${new Date().toLocaleTimeString()}</div>
                </div>
            `;
        }
    }

    // Main export functions
    async function findAllConversations() {
        log('🔍 Discovering conversations...');

        // Multiple selector strategies for Perplexity's interface
        const selectors = [
            'a[href*="/search/"]', // Common conversation URL pattern
            '[data-testid="thread-item"]', // Possible test ID
            '.conversation-item', // Generic class
            '[data-conversation-id]', // Data attribute
            'a[href^="/chat/"]' // Alternative URL pattern
        ];

        let conversations = [];

        for (const selector of selectors) {
            const elements = document.querySelectorAll(selector);
            if (elements.length > 0) {
                log(`✅ Found ${elements.length} conversations using selector: ${selector}`);

                conversations = Array.from(elements).map((element, index) => {
                    const link = element.href || element.querySelector('a')?.href;
                    const title = element.textContent?.trim() || 
                                element.querySelector('h3, h4, .title, [data-title]')?.textContent?.trim() ||
                                `Conversation ${index + 1}`;

                    return {
                        id: link ? link.split('/').pop() : `conv_${index}`,
                        title: sanitizeFilename(title),
                        url: link,
                        element: element
                    };
                }).filter(conv => conv.url); // Only include items with valid URLs

                break; // Use first successful selector
            }
        }

        if (conversations.length === 0) {
            throw new Error('No conversations found. You may need to navigate to your conversation history page.');
        }

        log(`📋 Discovered ${conversations.length} conversations total`);
        return conversations;
    }

    async function exportSingleConversation(conversation, index) {
        try {
            log(`📤 Exporting ${index + 1}: ${conversation.title}`);

            // Navigate to conversation if not already there
            if (!window.location.href.includes(conversation.id)) {
                window.location.href = conversation.url;
                await sleep(2000); // Wait for page load
            }

            // Try multiple strategies to find export functionality
            const exportStrategies = [
                // Strategy 1: Look for share/export button
                () => {
                    const shareBtn = document.querySelector('[data-testid="share-button"], .share-button, [aria-label*="share"], [aria-label*="export"]');
                    return shareBtn;
                },
                // Strategy 2: Look for three-dots menu
                () => {
                    const menuBtn = document.querySelector('[data-testid="menu-button"], .menu-button, [aria-label*="menu"], [aria-label*="options"]');
                    return menuBtn;
                },
                // Strategy 3: Look for download icon
                () => {
                    const downloadBtn = document.querySelector('[data-testid="download"], .download, [aria-label*="download"]');
                    return downloadBtn;
                }
            ];

            let exportButton = null;
            for (const strategy of exportStrategies) {
                exportButton = strategy();
                if (exportButton) break;
            }

            if (!exportButton) {
                throw new Error('Export button not found');
            }

            // Click export button
            exportButton.click();
            await sleep(1000);

            // Look for markdown/text export option
            const exportOptions = document.querySelectorAll('[data-format="markdown"], .export-markdown, [aria-label*="markdown"], [data-testid="export-markdown"]');

            if (exportOptions.length > 0) {
                exportOptions[0].click();
                await sleep(2000); // Wait for download
            } else {
                // Fallback: try to copy content manually
                const content = document.body.innerText;
                const blob = new Blob([content], { type: 'text/markdown' });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = `${new Date().toISOString().split('T')[0]}_${conversation.title}.md`;
                a.click();
                URL.revokeObjectURL(url);
            }

            log(`✅ Successfully exported: ${conversation.title}`, 'success');
            return true;

        } catch (error) {
            log(`❌ Failed to export ${conversation.title}: ${error.message}`, 'error');
            return false;
        }
    }

    // Main execution
    async function main() {
        const progressUI = createProgressUI();

        try {
            // Discovery phase
            updateProgress(0, 100, 'Discovering conversations...', 0);
            const conversations = await findAllConversations();

            // Export phase
            let successCount = 0;
            let errorCount = 0;

            for (let i = 0; i < conversations.length; i++) {
                const conversation = conversations[i];
                updateProgress(i, conversations.length, `Exporting: ${conversation.title}`, errorCount);

                const success = await exportSingleConversation(conversation, i);
                if (success) {
                    successCount++;
                } else {
                    errorCount++;
                }

                // Rate limiting
                await sleep(CONFIG.DELAY_BETWEEN_EXPORTS);
            }

            // Final summary
            updateProgress(conversations.length, conversations.length, 'Complete!', errorCount);

            log(`🎉 Export complete! Success: ${successCount}, Errors: ${errorCount}`, 'success');

            // Auto-remove progress UI after 10 seconds
            setTimeout(() => {
                progressUI?.remove();
            }, 10000);

        } catch (error) {
            log(`💥 Export failed: ${error.message}`, 'error');
            updateProgress(0, 100, `Error: ${error.message}`, 1);
        }
    }

    // Start the export
    await main();

})();
